### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by eee555** [ralokt/sweeping-view#1]
Would you like to publish this package to pypi, because I want to use this parser in my project. After publishing I can install it with pip commands, which will facilitate the automation of the project build.

**Comment by ralokt** [comment]
That's the plan!

I just didn't get around to it yet - I think there was a thing or two I still wanted to clean up... But yes, that would make a lot of sense for Scoreganizer deployment as well, it's on my TODO list (and just moved up quite a bit!).

**Comment by ralokt** [comment]
https://pypi.org/project/sweeping-view/ it is done! :)
